---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stumbleable-config
  namespace: stumbleable
data:
  # Node environment
  NODE_ENV: "production"
  
  # Service ports
  UI_PORT: "3000"
  DISCOVERY_PORT: "7001"
  INTERACTION_PORT: "7002"
  USER_PORT: "7003"
  CRAWLER_PORT: "7004"
  MODERATION_PORT: "7005"
  EMAIL_PORT: "7006"
  SCHEDULER_PORT: "7007"
  
  # Internal service URLs (for server-side calls)
  DISCOVERY_API_URL: "http://discovery-service:8080"
  INTERACTION_API_URL: "http://interaction-service:8080"
  USER_API_URL: "http://user-service:8080"
  CRAWLER_API_URL: "http://crawler-service:8080"
  MODERATION_API_URL: "http://moderation-service:8080"
  EMAIL_API_URL: "http://email-service:8080"
  SCHEDULER_API_URL: "http://scheduler-service:8080"
  
  # Public API URLs (for client-side calls)
  # These point to api.stumbleable.com subdomain with service-specific paths
  # Ingress rewrite rule: /servicename(/|$)(.*) -> /$2
  # So /discovery/api/next becomes /api/next at the service
  NEXT_PUBLIC_DISCOVERY_API_URL: "https://api.stumbleable.com/discovery"
  NEXT_PUBLIC_INTERACTION_API_URL: "https://api.stumbleable.com/interaction"
  NEXT_PUBLIC_USER_API_URL: "https://api.stumbleable.com/user"
  NEXT_PUBLIC_CRAWLER_API_URL: "https://api.stumbleable.com/crawler"
  NEXT_PUBLIC_MODERATION_API_URL: "https://api.stumbleable.com/moderation"
  NEXT_PUBLIC_EMAIL_API_URL: "https://api.stumbleable.com/email"
  NEXT_PUBLIC_SCHEDULER_API_URL: "https://api.stumbleable.com/scheduler"
  
  # Frontend URL (for CORS and email links)
  FRONTEND_URL: "https://stumbleable.com"
  
  # CORS - Allow both www and non-www domains
  ALLOWED_ORIGINS: "https://stumbleable.com,https://www.stumbleable.com"
  
  # Rate limiting (requests per minute per user/IP)
  RATE_LIMIT_MAX: "100"
  RATE_LIMIT_WINDOW: "60000"
  
  # Feature flags
  NEXT_TELEMETRY_DISABLED: "1"
  
  # Clerk custom authentication pages (must be absolute URLs for middleware)
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "https://stumbleable.com/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "https://stumbleable.com/sign-up"
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "https://stumbleable.com/dashboard"
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "https://stumbleable.com/onboarding"
  
  # Logging
  LOG_LEVEL: "info"
